### ISSUE TITLE
Inference for inline_script parameters from usages

### ISSUE THREAD

**Issue by TTFTCUTS** [DragonKnightOfBreeze/Paradox-Language-Support#54] opened 2023-11-28 01:53 UTC
As we expand the use of inline scripts in Gigastructural Engineering, it has become useful in several places to pass whole blocks of code as parameters. It would be very helpful if the parameters could be evaluated, much like how the scripts themselves infer context from where they are used.

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/49a248be-4505-4944-ab4c-981885157a01)
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/b60bc890-8f28-4e17-8f4a-59115d3be53e)

I understand that this might be a tricky request to fulfill, but being able to catch typos in these situations without making mock-ups first would be super useful.

Thank you, once again, for all of your hard work.

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 02:02
It's already implemented for simple cases.

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 02:09
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/623bb260-0d09-4fa0-9d7b-b7a5a9cd1842)

While the first option can enable the argument value inference (for scripted_triggers, scripted_effects, inline_scripts, single value or multiline), the second option can enable the inline script inference (for inline script files). And the leaving three options enable scope context inference in several situations, which may significantly affects performance.

If it's not work:
* There may be a bug, just update to 1.2.5.
* The case may be too complex.

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 02:10
Plz feedback your experience and ideas.

**Comment by TTFTCUTS** [comment] 2023-11-28 02:34
Well, those settings are already enabled:
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/f3300e83-5473-4c5c-98a7-a4062ab03953)

The current version of the plugin which I have is 1.2.4, but that's also the newest version the plugin settings give me...

A minimal example script which just takes one parameter and places it in-situ is the simplest case that I can think of
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/ba868ee0-2419-4989-a9b3-21e7d5897fe3)

But when it's used the parameter doesn't seem to be checked at all, and doesn't receive syntax highlighting.
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/20a2736a-c805-4e2d-80e6-39b99856a5e4)

So I'm not sure if I'm understanding what those settings are meant to be doing correctly.

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 02:36
Should be a bug in 1.2.4, update plugin to 1.2.5 on github releases and see what happens?

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 02:38
Also open xxx_traits.txt and see what happens to the inline script usages in these files?

**Comment by TTFTCUTS** [comment] 2023-11-28 02:46
I think I see what's going on now.

The trait files seem to work correctly, and if I add a second parameter which is the right hand side of an expression, like this:
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/235f6a0e-3e73-4562-b88f-780cc7f9ab5a)

Then _that_ parameter seems to work as expected, but the one which is meant to just put its whole content there does not.
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/6c9580bf-9a49-4932-8f3d-8d3579d5a2b8)

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 02:48
Should be a reproduced bug. 🙁

**Comment by TTFTCUTS** [comment] 2023-11-28 03:01
It seems to understand situations where the passed parameter is the right side of an expression, but not where it's a scope, or when it's a whole line or multiple lines.
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/c303a3c0-e3ce-4cb9-b745-e3c6631c8e50)

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/141568e5-c87b-479f-8485-16db3177b6c2)

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 04:21
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/df293502-cf13-49a2-a957-1a8f9ebd0194)

Found out it's a bug about double quotes.

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 04:24
A question, when typo `modifier` after `v = `, should plugin provide completion items and make inserted text surrounding with double quotes after applied, or just do not provide completion items (for there are no double quotes after `v = ` and whole line or multiline parameter value must be used in double quotes) ?

**Comment by TTFTCUTS** [comment] 2023-11-28 04:45
I am not entirely sure what you mean, but I do think it should still provide completion when typing inside quotes.

I think the ideal behaviour would be if it acted the same as a normal code block when inside quotes, almost as if they were braces instead, maybe only when multi-line? Unsure.

If I could type inside the parameter and it acts the same as where the code ends up being, that would be perfect - so in the very basic example again:
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/2deffe6d-b158-4bed-bb40-c74a68653122)
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/a85a7e9d-2be8-48dd-be87-2cc33f798b55)

Thank you for looking into this, it should be really useful for us.

@adriangaro probably has opinions on this too, as the only other person I know of who is doing weird things with inlines.

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 04:51
What do i say is that when I just typo `modifier` after `v = ` (neither `v = "` or `v = "\n`, `\n` means line break), should plugin provide completions for statements such as `modifier = {...}`? And if should , also make it surrounds with double quotes, and then, there is some text like `v = "modifier = {...}"`

**Comment by TTFTCUTS** [comment] 2023-11-28 05:05
Oh! Without quotes it should probably only suggest things which don't need quotes, like possible right-side values for expressions if the parameter is used that way.

**Comment by adriangaro** [comment] 2023-11-28 06:57
Some examples are 

https://github.com/Stellaris-Evolved/stellaris-evolved/blob/V0.9R8/common/inline_scripts/jobs/inline_evolved_job.txt

https://github.com/Stellaris-Evolved/stellaris-evolved/blob/V0.9R8/common/inline_scripts/jobs/inline_evolved_job_no_desc.txt

https://github.com/Stellaris-Evolved/stellaris-evolved/blob/V0.9R8/common/inline_scripts/jobs/inline_evolved_job_with_desc.txt

The first inline calls either of the following two depending on one of the parameters passed to the first one and delegates the rest.

**Comment by adriangaro** [comment] 2023-11-28 07:00
Also due to the interpolation of the `$job$` parameter into the modifier, the plugin has no idea that parameter is a job, so no autocomplete.

Being able to annotate that job is of the type job, would allow better highlighting.

I know it's a tall ask but would be really cool to be able to annotate parameters types, and maybe even add docs so they appear in context windows.

**Comment by adriangaro** [comment] 2023-11-28 07:02
If type annotation/comments are added, especially for triggered blocks, it would be amazing if the scope type could also be specified. (Yet again this is a nice to have in the context of inline script parameters, or parameters in general).

Thanks for the amazing work as always!

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 07:14
**Magic comment** or **annotation comment** is a good idea since it's already used by JetBrains officially in various template languages (e.g. JSP and FreeMarker), and I once considered this way.
But, the standards are to be determined, these is not only type annotation comments (or, cwt config annotation comments), but also some documentation comments and even scope context comments.

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 07:26
[Paradox-Language-Support-1.2.6.zip](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/files/13484869/Paradox-Language-Support-1.2.6.zip)

Here is a pre-release to support inference for whole line / multiline parameter values

**Comment by TTFTCUTS** [comment] 2023-11-28 07:40
Happy to say the first example above is highlighting now, but sadly it seems to be too complex for the plugin to properly infer context for, probably due to an inline call in the chain using a parameter in the script name.

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/e1698c5d-a1bd-4568-ba3a-95a6053a2210)

This is so much nicer than before though, so thank you!

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 07:49
What about inference for these inline script files, does it work well?

**Comment by TTFTCUTS** [comment] 2023-11-28 07:56
More simple scripts work very well:
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/7ba0840d-9421-47a1-ad9e-960078c58146)

The ones in the previous message don't, but that's probably because of these:

`giga_switch`
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/5f352de5-1b0c-437f-8435-5dde7694bda4)

`giga_toggled_code`
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/5436317/626fc2be-29d4-4da2-988d-0478508a5622)

Which conditionally leads to two scripts, `giga_toggled_code_case_0` and `giga_toggled_code_case_1`, the first of which is empty, for only including code if the `$toggle$` input is non-zero.

**Comment by TTFTCUTS** [comment] 2023-11-28 08:17
Technically speaking even if they were to infer everything correctly it would still break, as those toggles would resolve to 0 due to being cross-mod compatibility values, 0 when the other mod is not loaded and overwritten by that other mod to be 1.

So if the plugin somehow manages to untangle the flow in there, it would always end up leading to the empty `giga_toggled_code_case_0` because `has_bug_branch` is always zero in our development environment.

Some kind of override annotation would be required at very least to point it at `giga_toggled_code_case_1` instead, perhaps by telling `giga_switch` to always consider its `value` parameter to be 1 for the sake of inference.

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 08:20
Emmmmmmmmmmmmm... How do Chinese modders comment on your foxy?

**Comment by TTFTCUTS** [comment] 2023-11-28 08:28
I... don't understand what you mean.

What I mean to say by the previous comment is that I realised that the inference could never work for that particular script without extra hints because of the way we have structured it. It would always discard the parameters because their use is conditional upon another mod being present (because `has_bug_branch` is 0 when the Bug Branch mod is not present).

It seems to be working very well outside of those very complicated situations though, thank you for your efforts.

**Comment by DragonKnightOfBreeze** [comment] 2023-11-28 08:55
What I mean is that ... these are too many usages of paradox scripts' advance (or even very tricky) features in your mods, and so do some Chinese moddders'. Is may be sometimes necessary and convenient, but it also make paradox's languages not simple (or, not simple txt), and so do my plugin and cwtools.

**Comment by DragonKnightOfBreeze** [comment] 2023-11-29 03:39
I found out that the best way to provide advance language featues for implicit things, like parameter an event target's scope context, is just extended cwt config, rather than special comment in script files, or stupid inference.

**Comment by DragonKnightOfBreeze** [comment] 2023-12-01 02:37
It shall be mod-local (in `.config` which is under mod root directory) so that all mods can have its own extended cwt config files in a hidden directory to let the plugin to provide more support.
but currently user-defined cwt config files are project-local (in `.config` which is under project root directory), and each project & each game type has a config group.
May mod-local and project-local cwt configs are both supported.
There may be some refactoring, I'm not very sure.

**Comment by DragonKnightOfBreeze** [comment] 2023-12-01 06:50
f07784d53fc781c9849d47d05fcecbc6b56ef613

**Comment by adriangaro** [comment] 2023-12-09 17:46
Another small issue is with escaped characters inside multi line strings

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/c1fe17bb-7f8b-4a4f-9e5e-e807d0661b80)

**Comment by DragonKnightOfBreeze** [comment] 2023-12-09 17:59
Related optimizations and bug fixes will be resolved in 1.3.0 aka the next plugin version, mainly inference and documentation from custom cwt config, anf some other misc bugs. 
Should be finished in several weeks for there are some new games I will enjoy.

**Comment by DragonKnightOfBreeze** [comment] 2023-12-26 10:21
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/d1ae2363-0b1f-471a-a278-2ea1066ea83f)

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/f9c24e8d-6953-420b-93b2-b818b88e2e80)

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/34092666/2eb27f81-1197-44f6-b73d-8ee417d70a7d)

Features that supports custom documentation and scope context based on custom cwt files are implemented in v1.3.0 (in beta status).

See: https://windea.icu/Paradox-Language-Support/#/en/config.md

**Comment by adriangaro** [comment] 2024-01-05 11:59
Looking at the definitions, how can one specify the parameter type?

Also had some success defining the scripted effects as engine effects (since the above cannot mention parameter type and cardinality yet. Only issue is that the scripted effect itself does not use the below definition (makes sense since the below defines engine effects). Although probably doing the below is not intended

![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/5fd75fda-74c1-4b12-9711-60c52d3d4613)

**Comment by DragonKnightOfBreeze** [comment] 2024-01-05 12:14
@adriangaro What's the parameter type? identifier between ':' and ']'?
It's nothing special, can be 'some_key' or '<scripted_effect>' or some others.

for usage about aliases, you can refer to buitin config files and the guidance document.

**Comment by adriangaro** [comment] 2024-01-05 12:18
The identifier type is a scripted effect, mostly used the above so i could specify parameter type, since it is one of the more important use case to detail those.

I used those exact documents to try to use alias (since it fit this usage). But yeah ideally if the parameters definitions you added could support parameter type, it would be great.

Also seems the below, does not seem to set the event target scope, used the https://windea.icu/Paradox-Language-Support/#/en/config.md as reference
```values = {
    value[event_target] = {
         ## replace_scopes = { this = leader }
        tec_aiauth_pre_refragment
         ## replace_scopes = { this = leader }
        tec_aiauth_planetary_governing_node
         ## replace_scopes = { this = leader }
        tec_aiauth_ruler
         ## replace_scopes = { this = pop }
        tec_temp_pop
         ## replace_scopes = { this = leader }
        tec_aiauth_councilor
         ## replace_scopes = { this = leader }
        tec_replaced_ruler
         ## replace_scopes = { this = species }
        tec_ai_species
         ## replace_scopes = { this = species }
        tec_robot_search_species
         ## replace_scopes = { this = leader }
        tec_aiauth_pre_refragment
    }
}
```

**Comment by adriangaro** [comment] 2024-01-05 12:25
Also doing the below

```
definitions = {
    ## replace_scopes = { this = leader prev = country }
    ## type = scripted_effect
    tec_country_refragment_aiauth_node
}
```

seems to not set the `prev` scope
![image](https://github.com/DragonKnightOfBreeze/Paradox-Language-Support/assets/11583810/bc4f6de6-37a1-4c93-9541-a84a8822c6e2)

**Comment by DragonKnightOfBreeze** [comment] 2024-01-05 12:29
It's mentioned that you can use both literal and template expression as the key. 
For example, 'tec_value[xxx]_species' should matches any literal starts with 'tec_' and ends with '_species', no more limits for value[xxx]. Designed so, but not tested.
And alias is for declaration configs, not special configs like this.

**Comment by DragonKnightOfBreeze** [comment] 2024-01-05 12:30
prev cannot be replaced by ## replace_scopes, at least for PLS.

**Comment by DragonKnightOfBreeze** [comment] 2024-01-05 12:32
It's still a very beta feature and it's better to be discussed on somewhere else, like, just, discord.

**Comment by DragonKnightOfBreeze** [comment] 2024-01-05 12:34
https://discord.gg/RbU5U5TU

**Closed** 2024-05-26 17:22 UTC
Labels: enhancement
